.PHONY: save demo_deps demo_models demo_profile demo_doc demo_readme demo demo_clean

SIZES  ?= 224 320 640
RUNS   ?= 300
BATCH  ?= 1
WARMUP ?= 10
INTRA  ?= 1
INTER  ?= 1
CI     ?= 0

# 문서에 보여줄 최신 결과(최근 N개 파일 기준으로 latest 테이블 생성)
RECENT ?= 30

BENCH_DOC ?= BENCHMARKS.md

save:
	git add -A
	git commit -m "Auto-save $$(date -u +%Y-%m-%dT%H:%M:%SZ)" || true
	git push

demo_deps:
	poetry install
	poetry run python -m pip install -U pip
	poetry run python -m pip install torch onnxscript

demo_models: demo_deps
	mkdir -p models
	@set -e; \
	for s in $(SIZES); do \
		echo "==> Generating toy model: $${s}x$${s}"; \
		poetry run python scripts/make_toy_model.py --height $$s --width $$s --out models/toy$${s}.onnx; \
	done

demo_profile: demo_models
	mkdir -p reports
	@set -e; \
	ts=$$(date -u +%Y%m%d-%H%M%S); \
	for s in $(SIZES); do \
		echo "==> Profiling: models/toy$${s}.onnx"; \
		poetry run edgebench profile models/toy$${s}.onnx \
			--warmup $(WARMUP) \
			--runs $(RUNS) \
			--batch $(BATCH) \
			--height $$s --width $$s \
			--intra-threads $(INTRA) \
			--inter-threads $(INTER) \
			-o reports/toy$${s}__onnxruntime_cpu__b$(BATCH)__h$${s}w$${s}__r$(RUNS)__t$(INTRA)x$(INTER)__$${ts}.json; \
	done
	@echo "Done. Reports saved under ./reports/"

# BENCHMARKS.md 생성:
# 1) Latest: 최근 N개 파일만 고려하고, (모델/해상도별) 최신 1개만 남김
# 2) History: 전체 raw를 시간순으로 남김
demo_doc:
	@echo "==> Writing benchmark doc: $(BENCH_DOC)"
	@echo "# Benchmarks" > $(BENCH_DOC)
	@echo "" >> $(BENCH_DOC)
	@echo "> Auto-generated by \`make demo\` / CI" >> $(BENCH_DOC)
	@echo "" >> $(BENCH_DOC)
	poetry run edgebench summarize "reports/*.json" --mode latest --sort p99 --recent $(RECENT) >> $(BENCH_DOC)
	@echo "" >> $(BENCH_DOC)
	poetry run edgebench summarize "reports/*.json" --mode history --sort time >> $(BENCH_DOC)
	@echo "" >> $(BENCH_DOC)
	@echo "Saved: $(BENCH_DOC)"

demo_readme: demo_doc
	@echo "==> Updating README.md Benchmarks block"
	poetry run python scripts/update_readme.py --readme README.md --bench $(BENCH_DOC)

demo: demo_profile demo_readme
	@echo "✅ demo complete (updated $(BENCH_DOC) + README)"

demo_clean:
	rm -rf models reports $(BENCH_DOC)

# -------------------------
# CI-safe benchmark (PR friendly)
# - generates reports + BENCHMARKS.md only
# - does NOT touch README
# - does NOT git commit/push
# -------------------------
.PHONY: ci_bench
ci_bench: demo_profile demo_doc
	@echo "✅ ci_bench complete (reports + $(BENCH_DOC))"